version: '3.8'

services:
  postgreSql:
    restart: always
    platform: linux/x86_64
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - .docker/postgreSql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=ajexplorer
    networks:
      - server
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    restart: always
    platform: linux/x86_64
    build:
      context: ./
      dockerfile: ${DOCKERFILE:-Dockerfile.dev}
    ports:
      - '3000:3000'
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    networks:
      - server
    depends_on:
      postgreSql:
        condition: service_healthy

networks:
  server:
    driver: bridge

      